// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gyfmqedtupmpyfjujbwt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Zm1xZWR0dXBtcHlmanVqYnd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMTc2NDcsImV4cCI6MjA2Njc5MzY0N30.TGZka6qTsI8MGuPS9-4gw0ehAEVS_MnqGzeXdyrI7Ew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);